version: '3'
services:
  app:
    container_name: spring-boot-crm
    restart: always
    build: .
    ports:
      - '8081:8080'
    networks:
      - crm-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - crm-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crm

networks:
  crm-mysql:
