version: '3'
services:
  app:
    container_name: spring-boot-crm
    restart: always
    build: .
    ports:
      - '8080:8080'
    networks:
      - employee-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb

networks:
  employee-mysql:
